vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: /images/postes
            upload_destination: '%kernel.project_dir%/public/images/postes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
